// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatchPanda.Web.Db;

#nullable disable

namespace PatchPanda.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260521072912_AddSecurityUpdateEntities")]
    partial class AddSecurityUpdateEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AppVersionContainer", b =>
                {
                    b.Property<int>("ApplicationsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewerVersionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationsId", "NewerVersionsId");

                    b.HasIndex("NewerVersionsId");

                    b.ToTable("AppVersionContainer");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.AppVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppVersions");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.ComposeStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigFile")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PortainerManaged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stacks");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubRepo")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubVersionRegex")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreContainer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecondary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastVersionCheck")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MultiContainerAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideGitHubRepo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryGitHubRepos")
                        .HasColumnType("TEXT");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uptime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MultiContainerAppId");

                    b.HasIndex("StackId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.MultiContainerApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MultiContainerApps");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.UpdateAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailedCommand")
                        .HasColumnType("TEXT");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StdErr")
                        .HasColumnType("TEXT");

                    b.Property<string>("StdOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedPlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("StackId");

                    b.ToTable("UpdateAttempts");
                });

            modelBuilder.Entity("AppVersionContainer", b =>
                {
                    b.HasOne("PatchPanda.Web.Entities.Container", null)
                        .WithMany()
                        .HasForeignKey("ApplicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatchPanda.Web.Entities.AppVersion", null)
                        .WithMany()
                        .HasForeignKey("NewerVersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.Container", b =>
                {
                    b.HasOne("PatchPanda.Web.Entities.MultiContainerApp", "MultiContainerApp")
                        .WithMany("Containers")
                        .HasForeignKey("MultiContainerAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PatchPanda.Web.Entities.ComposeStack", "Stack")
                        .WithMany("Apps")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultiContainerApp");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.UpdateAttempt", b =>
                {
                    b.HasOne("PatchPanda.Web.Entities.Container", "Container")
                        .WithMany("UpdateAttempts")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatchPanda.Web.Entities.ComposeStack", "Stack")
                        .WithMany("UpdateAttempts")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.ComposeStack", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("UpdateAttempts");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.Container", b =>
                {
                    b.Navigation("UpdateAttempts");
                });

            modelBuilder.Entity("PatchPanda.Web.Entities.MultiContainerApp", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
